name: workFlowSecrets
on:
  push:
    branches:
      - workflow5

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        run: echo ${{ secrets.SECRET_VARIABLE }}

